export const cyclesData = [
  { name: 'ليسانس' },
  { name: 'ماستر' },
  { name: 'مهندس' }
];

export const roomsData = [
  { name: 'Amphi D', type: 'amphi', capacity: 200 },
  { name: 'Room 01/01', type: 'classroom', capacity: 40 },
  { name: 'Room 01/02', type: 'classroom', capacity: 40 },
  { name: 'Room 01/03', type: 'classroom', capacity: 40 },
  { name: 'Room 01/04', type: 'classroom', capacity: 40 },
  { name: 'Room 01/05', type: 'classroom', capacity: 40 },
  { name: 'Room 01/06', type: 'classroom', capacity: 40 },
  { name: 'Room 02/01', type: 'classroom', capacity: 40 },
  { name: 'Room 02/02', type: 'classroom', capacity: 40 },
  { name: 'Room 02/03', type: 'classroom', capacity: 40 },
  { name: 'IT Lab', type: 'lab', capacity: 25 },
  { name: 'Workshop', type: 'lab', capacity: 30 },
  { name: 'Metrology Lab', type: 'lab', capacity: 20 },
  { name: 'Materials.1 Lab', type: 'lab', capacity: 20 },
  { name: 'Materials.2 Lab', type: 'lab', capacity: 20 },
  { name: 'Heat Transfer Lab', type: 'lab', capacity: 20 },
  { name: 'Testing Lab', type: 'lab', capacity: 20 },
  { name: 'Turbomachinery Lab', type: 'lab', capacity: 20 },
];

export const levelsData = [
  { name: 'L1', cycleName: 'ليسانس' },
  { name: 'L2', cycleName: 'ليسانس' },
  { name: 'L3', cycleName: 'ليسانس' },
  { name: 'M1', cycleName: 'ماستر' },
  { name: 'M2', cycleName: 'ماستر' },
  { name: '1st Year', cycleName: 'مهندس' },
  { name: '2nd Year', cycleName: 'مهندس' },
  { name: '3rd Year', cycleName: 'مهندس' }
];

export const specialtiesData = [
  { name: 'Mechanical Engineering', levelKey: 'ليسانس_L2', field: 'LMD' },
  { name: 'Energetics', levelKey: 'ليسانس_L3', field: 'LMD' },
  { name: 'Materials Engineering', levelKey: 'ليسانس_L3', field: 'LMD' },
  { name: 'Mechanical Design', levelKey: 'ليسانس_L3', field: 'LMD' },
  { name: 'Industrial Maintenance', levelKey: 'ليسانس_L3', field: 'LMD' },
  { name: 'Energetics', levelKey: 'ماستر_M1', field: 'LMD' },
  { name: 'Materials and Surface Engineering', levelKey: 'ماستر_M1', field: 'LMD' },
  { name: 'Industrial Maintenance', levelKey: 'ماستر_M1', field: 'LMD' },
  { name: 'Renewable Energy in Mechanical Systems', levelKey: 'ماستر_M1', field: 'LMD' },
  { name: 'Energetics', levelKey: 'ماستر_M2', field: 'LMD' },
  { name: 'Industrial Maintenance', levelKey: 'ماستر_M2', field: 'LMD' },
  { name: 'Renewable Energy in Mechanical Systems', levelKey: 'ماستر_M2', field: 'LMD' },
  { name: 'Mechanical Engineering', levelKey: 'مهندس_2nd Year', field: 'Engineering' },
];

export const modulesData = [
  // Engineering - 2nd Year Engineer - Mechanical Engineering - S2
  { name: 'Computer-Aided Design', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Fluid Mechanics', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Information and Communication Technologies (ICT)', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Materials Science', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Measurement and Metrology', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Mechanical Design', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Numerical Analysis 2', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Steel Structures', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },
  { name: 'Strength of Materials', specialtyKey: 'Mechanical Engineering_مهندس_2nd Year', semester: 'S2' },

  // LMD - L2 - Mechanical Engineering - S2
  { name: 'Materials Science', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Strength of Materials', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Thermodynamics 2', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Mechanical Manufacturing', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Industrial Electricity', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Computer-Aided Design', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Mechanical Manufacturing Lab', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },
  { name: 'Strength of Materials Lab', specialtyKey: 'Mechanical Engineering_ليسانس_L2', semester: 'S2' },

  // LMD - L3 - Energetics - S1
  { name: 'Heat Transfer 1', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Measurement and Instrumentation', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Control and Automation', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Energy Conversion', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Machine Elements', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Fluid Mechanics 2', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Turbomachinery 1', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  { name: 'Environment and Sustainable Development', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S1' },
  // LMD - L3 - Energetics - S2
  { name: 'Internal Combustion Engines', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Turbomachinery 2', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Cryogenics', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Heat Transfer 2', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Refrigeration and Heat Pump Systems', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Renewable Energy', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Entrepreneurship', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },
  { name: 'Final Year Project', specialtyKey: 'Energetics_ليسانس_L3', semester: 'S2' },

  // LMD - L3 - Materials Engineering - S1
  { name: 'Ceramics and Glasses', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  { name: 'Metals and Alloys', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  { name: 'Continuum Mechanics', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  { name: 'Binders and Concretes', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  { name: 'Heat and Mass Transfer', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  { name: 'Analytical and Characterization Methods', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S1' },
  // LMD - L3 - Materials Engineering - S2
  { name: 'Polymers', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Composite Materials', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Environmental Impact of Materials', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Degradation and Protection of Materials', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Rheology of Materials', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Introduction to Biomaterials', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Entrepreneurship', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },
  { name: 'Final Year Project', specialtyKey: 'Materials Engineering_ليسانس_L3', semester: 'S2' },

  // LMD - L3 - Mechanical Design - S1
  { name: 'Machine Design', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'Control and Automation', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'Elasticity', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'Analytical Mechanics', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'CAD/CAM', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'Metrology', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  { name: 'Strength of Materials 2', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S1' },
  // LMD - L3 - Mechanical Design - S2
  { name: 'Internal Combustion Engines', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Non-metallic Materials', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Theory of Machines', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Hydraulic and Pneumatic Systems', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Machine Design 2', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Heat Transfer', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Structural Dynamics', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Entrepreneurship', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },
  { name: 'Final Year Project', specialtyKey: 'Mechanical Design_ليسانس_L3', semester: 'S2' },

  // LMD - L3 - Industrial Maintenance - S1
  { name: 'Applied Electronics', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Elements of Heat Transfer', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Machine Elements', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Computer-Aided Maintenance Management (CAMM)', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Maintenance Organization and Methods', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Sensors and Metrology', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  { name: 'Applied Electrical Engineering', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S1' },
  // LMD - L3 - Industrial Maintenance - S2
  { name: 'Industrial Robotics', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Signal Processing', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Condition-Based Maintenance Tools', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Thermal and Hydraulic Machinery Technology', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Reliability', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Structural Dynamics', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Internal Combustion Engines', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Entrepreneurship', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },
  { name: 'Final Year Project', specialtyKey: 'Industrial Maintenance_ليسانس_L3', semester: 'S2' },

  // LMD Master - M1 - Energetics - S1
  { name: 'Advanced Heat and Mass Transfer', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Numerical Methods', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Fluid Mechanics', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  { name: 'Thermal Machines', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Python Programming', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  { name: 'Environment, Protection and Control', specialtyKey: 'Energetics_ماستر_M1', semester: 'S1' },
  // LMD Master - M1 - Energetics - S2
  { name: 'Thermal Drying', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Finite Volume Methods', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Gas Dynamics', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Advanced Turbomachinery', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Heating and Air Conditioning', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Compliance with Ethical Standards, Rules, and Integrity', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },
  { name: 'Elements of Applied Artificial Intelligence', specialtyKey: 'Energetics_ماستر_M1', semester: 'S2' },

  // LMD Master - M1 - Materials and Surface Engineering - S1
  { name: 'Ferrous and Non-Ferrous Materials', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Phase Transformations', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Materials Forming', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Mechanical Properties of Materials', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Surface Engineering', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Applied Numerical Methods', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Python Programming', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  { name: 'Environment, Protection and Control', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S1' },
  // LMD Master - M1 - Materials and Surface Engineering - S2
  { name: 'Physico-Chemical and Mechanical Properties of Polymers', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Fracture Mechanics', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Finite Element Methods 2', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Diffusion and Phase Transformation', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Mechanical Behavior of Composite and Multi-Materials', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Heat Treatments', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Mechanical Testing 2', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Elements of Applied Artificial Intelligence', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },
  { name: 'Compliance with Ethical Standards, Rules, and Integrity', specialtyKey: 'Materials and Surface Engineering_ماستر_M1', semester: 'S2' },

  // LMD Master - M1 - Industrial Maintenance - S1
  { name: 'Statistical Methods and Sampling', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Applied Thermodynamics', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Continuum Mechanics', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Structural Dynamics', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Maintenance Strategy', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Signal Processing', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Python Programming', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  { name: 'Environment, Protection and Control', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S1' },
  // LMD Master - M1 - Industrial Maintenance - S2
  { name: 'Computerized Maintenance Management System (CMMS)', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Rotating Machinery Vibration', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'System Reliability', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Finite Element Method', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Smart Sensors', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Mechanical Design', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Manufacturing Processes and Machine Tools', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Elements of Applied Artificial Intelligence', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },
  { name: 'Compliance with Ethical Standards, Rules, and Integrity', specialtyKey: 'Industrial Maintenance_ماستر_M1', semester: 'S2' },

  // LMD Master - M1 - Renewable Energy in Mechanical Systems - S1
  { name: 'Applied Numerical Methods', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Fluid Mechanics', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Thermodynamics and Transport Phenomena', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  { name: 'Renewable Resources and Meteorology', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  { name: 'Advanced Python Programming', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  { name: 'Environment, Protection and Control', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S1' },
  // LMD Master - M1 - Renewable Energy in Mechanical Systems - S2
  { name: 'Hydroelectric and Wind Energy', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Solar Radiation', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Thermal Solar Energy and Applications', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Installation and Sizing of Renewable Energy Projects', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Energy Conversion', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Advanced Heat Transfer and Transport Phenomena', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Elements of Applied Artificial Intelligence', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },
  { name: 'Control and Regulation', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M1', semester: 'S2' },

  // LMD Master - M2 - Energetics - S1
  { name: 'CFD and Software', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Heat Exchangers', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Optimization', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Propulsion Mechanics', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Advanced Internal Combustion Engines', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Cryogenics', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Reverse Engineering', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },
  { name: 'Dissertation Design', specialtyKey: 'Energetics_ماستر_M2', semester: 'S1' },

  // LMD Master - M2 - Industrial Maintenance - S1
  { name: 'Tribology and Lubrication of Mechanical Systems', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Applied Acoustics', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Fracture Mechanics and Damage Analysis', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Failure Detection Techniques', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Industrial Automation', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Reverse Engineering', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },
  { name: 'Vibration-Based Diagnostics', specialtyKey: 'Industrial Maintenance_ماستر_M2', semester: 'S1' },

  // LMD Master - M2 - Renewable Energy in Mechanical Systems - S1
  { name: 'Building Energy and Thermal Efficiency', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Maintenance of Renewable Energy Systems', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Solar Cooling and Air Conditioning', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Working Fluids, Materials and Storage Devices', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Fuel Cells and Hydrogen Production', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Photovoltaic Solar Energy and Applications', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
  { name: 'Techno-Economic Analysis and Project Management for Renewable Energy', specialtyKey: 'Renewable Energy in Mechanical Systems_ماستر_M2', semester: 'S1' },
];

export const teachersData = [
  { name: 'Tahar MANSOURI', email: 't.mansouri@lagh-univ.dz', role: 'admin' },
  { name: 'Aissa Hadjaissa', email: 'a.hadjaissa@lagh-univ.dz', role: 'teacher' },
  { name: 'Ahmed YOUSFI', email: 'a.yousfi@lagh-univ.dz', role: 'teacher' },
  { name: 'Ahmed BENSENOUCI', email: 'a.bensenouci@lagh-univ.dz', role: 'teacher' },
  { name: 'Abdelkader Djilali HAMMOU', email: 'a.hammou@lagh-univ.dz', role: 'teacher' },
  { name: 'Ahmida REZIG', email: 'a.rezig@lagh-univ.dz', role: 'teacher' },
  { name: 'Belkacem BOUALI', email: 'b.bouali@lagh-univ.dz', role: 'teacher' },
  { name: 'Abdelkader Ilyes Ameur', email: 'ak.ameur@lagh-univ.dz', role: 'teacher' },
  { name: 'Boubaker ZEGNINI', email: 'b.zegnini@lagh-univ.dz', role: 'teacher' },
  { name: 'Ahmed HIRECHE', email: 'a.hireche@lagh-univ.dz', role: 'teacher' },
  { name: 'Belkacem BENSMAIN', email: 'be.bensmain@lagh-univ.dz', role: 'teacher' },
  { name: 'Djelloul GUERIBIZ', email: 'd.gueribiz@lagh-univ.dz', role: 'teacher' },
  { name: 'Lhadjaissa benhorma', email: 'h.benhorma@lagh-univ.dz', role: 'teacher' },
  { name: 'Khaled ABDESSEMED', email: 'k.abdessemed@lagh-univ.dz', role: 'teacher' },
  { name: 'ahmed Benchatti', email: 'a.benchatti@lagh-univ.dz', role: 'teacher' },
  { name: 'Khaled BENSAYAH', email: 'k.bensayah@lagh-univ.dz', role: 'teacher' },
  { name: 'Badiaa GHERNAOUT', email: 'b.ghernaout@lagh-univ.dz', role: 'teacher' },
  { name: 'abdelhadi benhorma', email: 'hadibenhorma@gmail.com', role: 'teacher' },
  { name: 'Ameur MECHRAOUI', email: 'a.mechraoui@lagh-univ.dz', role: 'teacher' },
  { name: 'Medjelled Ahmed', email: 'a.medjelled@lagh-univ.dz', role: 'teacher' },
  { name: 'Hamza SOUALHI', email: 'h.soualhi@lagh-univ.dz', role: 'teacher' },
  { name: 'Lahcene BELLAHCENE', email: 'l.bellahcene@lagh-univ.dz', role: 'teacher' },
  { name: 'Maati Ahmed', email: 'a.maati@lagh-univ.dz', role: 'teacher' },
  { name: 'Mokhtar AOUISSI', email: 'm.aouissi@lagh-univ.dz', role: 'teacher' },
  { name: 'Mohamed BELHADJ', email: 'm.belhadj@lagh-univ.dz', role: 'teacher' },
  { name: 'Mokhtaria MESRI', email: 'm.mesri@lagh-univ.dz', role: 'teacher' },
  { name: 'Lakhdar HACHANI', email: 'l.hachani@lagh-univ.dz', role: 'teacher' },
  { name: 'MUSTAPHA NOUREDDINE', email: 'm.noureddine@lagh-univ.dz', role: 'teacher' },
  { name: 'Kelthoum HACHANI', email: 'k.hachani@lagh-univ.dz', role: 'teacher' },
  { name: 'Atallah BENMESSAOUD', email: 'ata.benmessaoud@gmail.com', role: 'teacher' },
  { name: 'Yakoub AYEB', email: 'y.ayeb@lagh-univ.dz', role: 'teacher' },
  { name: 'Omar ALLAOUI', email: 'o.allaoui@lagh-univ.dz', role: 'teacher' },
  { name: 'Sami ZIDELMEL', email: 's.zidelmel@lagh-univ.dz', role: 'teacher' },
  { name: 'Salim BELAID', email: 's.belaid@lagh-univ.dz', role: 'teacher' },
  { name: 'Said BOUABDALLAH', email: 's.bouabdallah@lagh-univ.dz', role: 'teacher' },
  { name: 'karim rayane', email: 'rayanek@lagh-univ.dz', role: 'teacher' },
  { name: 'Mohamed RAHMANI', email: 'm.rahmani@lagh-univ.dz', role: 'teacher' },
  { name: 'Maria Hanan REGUE', email: 'mh.regue@lagh-univ.dz', role: 'teacher' },
  { name: 'Mohamed TEGGAR', email: 'm.teggar@lagh-univ.dz', role: 'teacher' },
];
